###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: orchid-demo-memcached

    mysql:
      image: mysql:5
      container_name: orchid-demo-mysql
      working_dir: /application
      volumes:
        - ./orchid:/application
        - ./data/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=demo123
        - MYSQL_DATABASE=orchid
        - MYSQL_USER=orchid
        - MYSQL_PASSWORD=orchid
      ports:
        - "9003:3306"

    webserver:
      image: nginx:alpine
      container_name: orchid-demo-webserver
      working_dir: /application
      volumes:
          - ./orchid:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9090:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: orchid-demo-php-fpm
      working_dir: /application
      volumes:
        - ./orchid:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

